# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180829_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='header',
            field=models.CharField(max_length=256),
        ),
    ]
