# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180829_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='address',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='loginDate',
            field=models.DateTimeField(null=True),
        ),
    ]
