# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='product_image',
            new_name='productImage',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.myUser'),
        ),
    ]
