# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20180830_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='productImage',
            field=models.ImageField(upload_to='static'),
        ),
    ]
