# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20180830_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='imgHeight',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='productitem',
            name='imgWidth',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='productImage',
            field=models.ImageField(height_field='imgHeight', upload_to='image', width_field='imgWidth'),
        ),
    ]
