# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20180830_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='productImage',
            field=models.ImageField(height_field='imgHeight', upload_to='images', width_field='imgWidth'),
        ),
    ]
