# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20180830_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfrom',
            name='orderState',
            field=models.IntegerField(choices=[(0, '\u5173\u95ed'), (1, '\u5f85\u4ed8\u6b3e'), (2, '\u5df2\u4ed8\u6b3e'), (3, '\u5df2\u53d1\u8d27'), (4, '\u5df2\u6536\u8d27'), (5, '\u5b8c\u6210')], verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
