# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20180830_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
