# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20180830_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='idDefault',
            field=models.BooleanField(default=False),
        ),
    ]
